// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: dummydata.proto

package dummydata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message
type DummyDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DummyDataRequest) Reset() {
	*x = DummyDataRequest{}
	mi := &file_dummydata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DummyDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DummyDataRequest) ProtoMessage() {}

func (x *DummyDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dummydata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DummyDataRequest.ProtoReflect.Descriptor instead.
func (*DummyDataRequest) Descriptor() ([]byte, []int) {
	return file_dummydata_proto_rawDescGZIP(), []int{0}
}

func (x *DummyDataRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// Response message with dummy data
type DummyDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value         int32                  `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	CreatedAt     *Timestamp             `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DummyDataResponse) Reset() {
	*x = DummyDataResponse{}
	mi := &file_dummydata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DummyDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DummyDataResponse) ProtoMessage() {}

func (x *DummyDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dummydata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DummyDataResponse.ProtoReflect.Descriptor instead.
func (*DummyDataResponse) Descriptor() ([]byte, []int) {
	return file_dummydata_proto_rawDescGZIP(), []int{1}
}

func (x *DummyDataResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DummyDataResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DummyDataResponse) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *DummyDataResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DummyDataResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *DummyDataResponse) GetCreatedAt() *Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Timestamp message
type Timestamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seconds       int64                  `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Nanos         int32                  `protobuf:"varint,2,opt,name=nanos,proto3" json:"nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timestamp) Reset() {
	*x = Timestamp{}
	mi := &file_dummydata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timestamp) ProtoMessage() {}

func (x *Timestamp) ProtoReflect() protoreflect.Message {
	mi := &file_dummydata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timestamp.ProtoReflect.Descriptor instead.
func (*Timestamp) Descriptor() ([]byte, []int) {
	return file_dummydata_proto_rawDescGZIP(), []int{2}
}

func (x *Timestamp) GetSeconds() int64 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *Timestamp) GetNanos() int32 {
	if x != nil {
		return x.Nanos
	}
	return 0
}

var File_dummydata_proto protoreflect.FileDescriptor

const file_dummydata_proto_rawDesc = "" +
	"\n" +
	"\x0fdummydata.proto\x12\tdummydata\"1\n" +
	"\x10DummyDataRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"\xb8\x01\n" +
	"\x11DummyDataResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x05R\x05value\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x123\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x14.dummydata.TimestampR\tcreatedAt\";\n" +
	"\tTimestamp\x12\x18\n" +
	"\aseconds\x18\x01 \x01(\x03R\aseconds\x12\x14\n" +
	"\x05nanos\x18\x02 \x01(\x05R\x05nanos2\xb1\x01\n" +
	"\x10DummyDataService\x12K\n" +
	"\fGetDummyData\x12\x1b.dummydata.DummyDataRequest\x1a\x1c.dummydata.DummyDataResponse\"\x00\x12P\n" +
	"\x0fStreamDummyData\x12\x1b.dummydata.DummyDataRequest\x1a\x1c.dummydata.DummyDataResponse\"\x000\x01B6Z4github.com/alfredfrancis/dummy-grpc-server/dummydatab\x06proto3"

var (
	file_dummydata_proto_rawDescOnce sync.Once
	file_dummydata_proto_rawDescData []byte
)

func file_dummydata_proto_rawDescGZIP() []byte {
	file_dummydata_proto_rawDescOnce.Do(func() {
		file_dummydata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dummydata_proto_rawDesc), len(file_dummydata_proto_rawDesc)))
	})
	return file_dummydata_proto_rawDescData
}

var file_dummydata_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_dummydata_proto_goTypes = []any{
	(*DummyDataRequest)(nil),  // 0: dummydata.DummyDataRequest
	(*DummyDataResponse)(nil), // 1: dummydata.DummyDataResponse
	(*Timestamp)(nil),         // 2: dummydata.Timestamp
}
var file_dummydata_proto_depIdxs = []int32{
	2, // 0: dummydata.DummyDataResponse.created_at:type_name -> dummydata.Timestamp
	0, // 1: dummydata.DummyDataService.GetDummyData:input_type -> dummydata.DummyDataRequest
	0, // 2: dummydata.DummyDataService.StreamDummyData:input_type -> dummydata.DummyDataRequest
	1, // 3: dummydata.DummyDataService.GetDummyData:output_type -> dummydata.DummyDataResponse
	1, // 4: dummydata.DummyDataService.StreamDummyData:output_type -> dummydata.DummyDataResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dummydata_proto_init() }
func file_dummydata_proto_init() {
	if File_dummydata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dummydata_proto_rawDesc), len(file_dummydata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dummydata_proto_goTypes,
		DependencyIndexes: file_dummydata_proto_depIdxs,
		MessageInfos:      file_dummydata_proto_msgTypes,
	}.Build()
	File_dummydata_proto = out.File
	file_dummydata_proto_goTypes = nil
	file_dummydata_proto_depIdxs = nil
}
